version: 0.2

env:
  git-credential-helper: yes

proxy:
  logs: yes

phase:
  install:
    runtime-versions:
      docker: 18
      python: 3.8

  pre_build:
    commands:
      - make lambdas
  
  build:
    commands:
      - make deploy